#ifdef OUR_PERSIST

#ifndef SHARE_GC_NVMCARD_NVMCARDTABLEBARRIERSETASSEMBLER_HPP
#define SHARE_GC_NVMCARD_NVMCARDTABLEBARRIERSETASSEMBLER_HPP

#include "utilities/macros.hpp"

#include CPU_HEADER(gc/nvm_card/nvmCardTableBarrierSetAssembler)

#endif // SHARE_GC_NVMCARD_NVMCARDTABLEBARRIERSETASSEMBLER_HPP

#endif // OUR_PERSIST
