#ifdef OUR_PERSIST

#ifndef SHARE_GC_NVMCARD_NVMCARDTABLEBARRIERSET_INLINE_HPP
#define SHARE_GC_NVMCARD_NVMCARDTABLEBARRIERSET_INLINE_HPP

#include "gc/nvm_card/nvmCardTableBarrierSet.hpp"
#include "nvm/ourPersist.inline.hpp"

#endif // SHARE_GC_NVMCARD_NVMCARDTABLEBARRIERSET_INLINE_HPP

#endif // OUR_PERSIST
