#ifdef AUTO_PERSIST

#ifndef SHARE_GC_AUTOPERSIST_AUTOPERSISTTABLEBARRIERSETASSEMBLER_HPP
#define SHARE_GC_AUTOPERSIST_AUTOPERSISTTABLEBARRIERSETASSEMBLER_HPP

#include "utilities/macros.hpp"

#include CPU_HEADER(gc/auto_persist/autoPersistBarrierSetAssembler)

#endif // SHARE_GC_AUTOPERSIST_AUTOPERSISTTABLEBARRIERSETASSEMBLER_HPP

#endif // AUTO_PERSIST
